---
title: "UCSAS 2024"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
source("./scripts/data.getter.R")
source("./scripts/data.prepper.R")
source("./scripts/data.picker.R")

source("./scripts/model.fitter.R")
source("./scripts/model.predictor.R")
```

```{r}
# utility functions
na.pad <- function(x,len){
    x[1:len]
}

makePaddedDataFrame <- function(l,...){
    maxlen <- max(sapply(l,length))
    data.frame(lapply(l,na.pad,len=maxlen),...)
}
```


```{r}
# clean and processed DF
df <- prepare_data(get_data())
top_countries <- read_csv("./raw_data/top_countries.csv",
                          show_col_types = FALSE)
c3_countries <- read_csv("./raw_data/criteria3.csv", 
                         show_col_types = FALSE)
c45_competitors <- read_csv("./raw_data/criteria4_5.csv",
                            show_col_types = FALSE)
hu_competitors <- read_csv("./raw_data/host_universality.csv",
                           show_col_types = FALSE)
named_competitors <- bind_rows(
  c45_competitors,
  hu_competitors
)
```

# Fit Model and get global predictions (one shot)

```{r}
# get a model for each (apparatus, gender) pair
lm_models <- fit_lm_model(df)
# using whole data frame, get predictions of every athlete's e_score now
predictions <- predict_scores(df, lm_models)
```

# Load Competitors

```{r} 
# Criteria 1: WCH 2022 Team Final
# Criteria 2: WCH 2023 Team Qualifications
w12 <- process_team_competitors(predictions, top_countries, named_competitors, "w")
m12 <- process_team_competitors(predictions, top_countries, named_competitors, "m")

# Criteria 3: the three countries in c3[[gender]] each get to send one qualifier
w3 <- get_top_non_usa(predictions, c3_countries, named_competitors, "w", n = 1)
m3 <- get_top_non_usa(predictions, c3_countries, named_competitors, "m", n = 1)

# Criteria 4: WCH 2023 All-Around Qualification (8 men, 8 women)
# Criteria 5: WCH 2023 Apparatus Final Qualification (6 men, 6 women)
w45 <- get_exact_names(predictions, c45_competitors[["w"]])
m45 <- get_exact_names(predictions, c45_competitors[["m"]])

# Host Country Place and Universality Place
# as of 2023-12-11 only has been determined for women
whu <- get_exact_names(predictions, hu_competitors[["w"]])
mhu <- get_exact_names(predictions, hu_competitors[["m"]])

women <- bind_rows(w12, w3, w45, whu)
men <- bind_rows(m12, m3, m45, mhu)

all_named <- makePaddedDataFrame(list(w = women$name, m = men$name))

# Criteria 6 and 7 yet to be determined as of 2023-12-11
# COMPETITORS NOT IN LIST RANDOMLY CHOSEN FOR CRITERIA 6 AND 7

# Pick 96 - 77 = 19 men
m67 <- get_top_remaining(predictions, top_countries, all_named, "m", n = 19)

# Pick 96 - 82 = 14 women
w67 <- get_top_remaining(predictions, top_countries, all_named, "w", n = 14)

women <- bind_rows(women, w67)
men <- bind_rows(men, m67)
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```